# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(default=b'none', max_length=100)),
                ('customer_id', models.CharField(default=b'none', max_length=100)),
                ('address1', models.CharField(default=b'none', max_length=100)),
                ('address2', models.CharField(default=b'none', max_length=100)),
                ('address3', models.CharField(default=b'none', max_length=100)),
                ('country', models.CharField(default=b'none', max_length=100)),
                ('state', models.CharField(default=b'none', max_length=100)),
                ('city', models.CharField(default=b'none', max_length=100)),
                ('bill_address1', models.CharField(default=b'none', max_length=100)),
                ('bill_address2', models.CharField(default=b'none', max_length=100)),
                ('bill_address3', models.CharField(default=b'none', max_length=100)),
                ('bill_country', models.CharField(default=b'none', max_length=100)),
                ('bill_state', models.CharField(default=b'none', max_length=100)),
                ('bill_city', models.CharField(default=b'none', max_length=100)),
                ('primary_contact', models.IntegerField(default=0)),
                ('telephone', models.IntegerField(default=0)),
                ('telephone_ext', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('toll_free', models.IntegerField(default=0)),
                ('secondary_contact', models.IntegerField(default=0)),
                ('secondary_email', models.IntegerField(default=0)),
                ('billing_email', models.IntegerField(default=0)),
                ('bill_telephone', models.IntegerField(default=0)),
                ('bill_ext', models.IntegerField(default=0)),
                ('advanced_internal', models.CharField(default=b'none', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LoadModels',
            fields=[
                ('load', models.AutoField(serialize=False, primary_key=True)),
                ('bill_to', models.CharField(default=b'None', max_length=100)),
                ('dispatcher', models.CharField(default=b'None', max_length=100)),
                ('sales', models.CharField(default=b'None', max_length=50)),
                ('status', models.CharField(default=b'None', max_length=50)),
                ('types', models.CharField(default=b'None', max_length=50)),
                ('rate', models.IntegerField(default=0)),
                ('pd', models.IntegerField(default=0)),
                ('usd', models.IntegerField(default=0)),
                ('carrier', models.CharField(default=b'None', max_length=100)),
                ('driver', models.CharField(default=b'None', max_length=100)),
                ('truck', models.CharField(default=b'None', max_length=100)),
                ('trailer', models.CharField(default=b'None', max_length=100)),
                ('flat_rate', models.IntegerField(default=b'None', max_length=100)),
                ('shipper', models.CharField(default=b'None', max_length=200)),
                ('location', models.CharField(default=b'None', max_length=200)),
                ('ship_date', models.DateTimeField(null=True)),
                ('description', models.CharField(default=b'None', max_length=200)),
                ('ship_type', models.CharField(default=b'None', max_length=200)),
                ('ship_qty', models.IntegerField(default=0)),
                ('ship_weight', models.IntegerField(default=0)),
                ('shipping_notes', models.CharField(default=b'None', max_length=200)),
                ('ship_po', models.IntegerField(default=0)),
                ('custom_broker', models.CharField(default=b'None', max_length=200)),
                ('consignee', models.CharField(default=b'None', max_length=200)),
                ('c_location', models.CharField(default=b'None', max_length=200)),
                ('c_date', models.DateTimeField(null=True)),
                ('c_description', models.CharField(default=b'None', max_length=200)),
                ('c_type', models.CharField(default=b'None', max_length=200)),
                ('c_qty', models.IntegerField(default=0)),
                ('c_weight', models.IntegerField(default=0)),
                ('delivery_notes', models.CharField(default=b'None', max_length=200)),
                ('c_po', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SingleDriver',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('driver_name', models.CharField(default=b'none', max_length=100)),
                ('telephone', models.IntegerField(default=0)),
                ('cell_phone', models.IntegerField(default=0)),
                ('pager', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(default=b'none', max_length=100)),
                ('country', models.CharField(default=b'none', max_length=100)),
                ('state', models.CharField(default=b'none', max_length=100)),
                ('city', models.CharField(default=b'none', max_length=100)),
                ('zip_code', models.IntegerField(default=0)),
                ('dob', models.DateTimeField(null=True)),
                ('hire_date', models.DateTimeField(null=True)),
                ('last_medical', models.DateTimeField(null=True)),
                ('last_drug_test', models.DateTimeField(null=True)),
                ('next_drug_test', models.DateTimeField(null=True)),
                ('passport_expiry', models.DateTimeField(null=True)),
                ('license_no', models.CharField(default=b'none', max_length=100)),
                ('license_expiry', models.DateTimeField(null=True)),
                ('fast_card_expiry', models.DateTimeField(null=True)),
                ('hazmat_expiry', models.DateTimeField(null=True)),
                ('internal_notes', models.CharField(default=b'none', max_length=200)),
                ('pay', models.IntegerField(default=0)),
                ('pay_type', models.CharField(default=b'none', max_length=100)),
                ('currency', models.CharField(default=b'USD', max_length=100)),
                ('pay_details', models.CharField(default=b'none', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TeamDriver',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('driver_name', models.CharField(default=b'none', max_length=100)),
                ('telephone', models.IntegerField(default=0)),
                ('cell_phone', models.IntegerField(default=0)),
                ('pager', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(default=b'none', max_length=100)),
                ('country', models.CharField(default=b'none', max_length=100)),
                ('state', models.CharField(default=b'none', max_length=100)),
                ('city', models.CharField(default=b'none', max_length=100)),
                ('zip_code', models.IntegerField(default=0)),
                ('dob', models.DateTimeField(null=True)),
                ('hire_date', models.DateTimeField(null=True)),
                ('last_medical', models.DateTimeField(null=True)),
                ('last_drug_test', models.DateTimeField(null=True)),
                ('next_drug_test', models.DateTimeField(null=True)),
                ('passport_expiry', models.DateTimeField(null=True)),
                ('license_no', models.CharField(default=b'none', max_length=100)),
                ('license_expiry', models.DateTimeField(null=True)),
                ('fast_card_expiry', models.DateTimeField(null=True)),
                ('hazmat_expiry', models.DateTimeField(null=True)),
                ('internal_notes', models.CharField(default=b'none', max_length=200)),
                ('pay', models.IntegerField(default=0)),
                ('pay_type', models.CharField(default=b'none', max_length=100)),
                ('currency', models.CharField(default=b'USD', max_length=100)),
                ('pay_details', models.CharField(default=b'none', max_length=200)),
                ('driver_name2', models.CharField(default=b'none', max_length=100)),
                ('telephone2', models.IntegerField(default=0)),
                ('cell_phone2', models.IntegerField(default=0)),
                ('pager2', models.IntegerField(default=0)),
                ('email2', models.EmailField(max_length=254, null=True)),
                ('address2', models.CharField(default=b'none', max_length=100)),
                ('country2', models.CharField(default=b'none', max_length=100)),
                ('state2', models.CharField(default=b'none', max_length=100)),
                ('city2', models.CharField(default=b'none', max_length=100)),
                ('zip_code2', models.IntegerField(default=0)),
                ('dob2', models.DateTimeField(null=True)),
                ('hire_date2', models.DateTimeField(null=True)),
                ('last_medical2', models.DateTimeField(null=True)),
                ('last_drug_test2', models.DateTimeField(null=True)),
                ('next_drug_test2', models.DateTimeField(null=True)),
                ('passport_expiry2', models.DateTimeField(null=True)),
                ('license_no2', models.CharField(default=b'none', max_length=100)),
                ('license_expiry2', models.DateTimeField(null=True)),
                ('fast_card_expiry2', models.DateTimeField(null=True)),
                ('hazmat_expiry2', models.DateTimeField(null=True)),
                ('internal_notes2', models.CharField(default=b'none', max_length=200)),
                ('pay2', models.IntegerField(default=0)),
                ('pay_type2', models.CharField(default=b'none', max_length=100)),
                ('currency2', models.CharField(default=b'USD', max_length=100)),
                ('pay_details2', models.CharField(default=b'none', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('truck_no', models.IntegerField(unique=True)),
                ('truck_type', models.CharField(default=b'none', max_length=100)),
                ('license_plate', models.CharField(default=b'none', max_length=100)),
                ('plate_expiry', models.DateTimeField(default=b'none')),
                ('inspection_expiry', models.DateTimeField(null=True)),
                ('internal_notes', models.CharField(default=b'none', max_length=200)),
                ('status', models.CharField(default=b'none', max_length=100)),
                ('ownership', models.CharField(default=b'none', max_length=100)),
                ('mileage', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField(null=True)),
                ('axles', models.CharField(default=b'none', max_length=100)),
                ('fuel_type', models.CharField(default=b'none', max_length=100)),
                ('deactivation', models.DateTimeField(null=True)),
                ('registered_state', models.CharField(default=b'none', max_length=100)),
                ('insurance_no', models.CharField(default=b'none', max_length=100)),
                ('gross_weight', models.IntegerField(default=0)),
                ('vehicle_id', models.CharField(unique=True, max_length=100)),
                ('dot_expiry', models.DateTimeField(null=True)),
            ],
        ),
    ]
